spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoppingmall?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 953f431e46da04f08274b90f73ff43a0
            client-secret: wqeq2
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: GET
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - nickname
          naver:
            client-id: aqITYOSde48YsU2LTjJB
            client-secret: 6VKZWAqoab
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,gender,birthyear,mobile
            client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


logging:
  level:
    com.pwang.project : Debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
